# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "minomina-stacks"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
s3_bucket = "minomina-stacks2"
region = "us-east-2"
parameter_overrides = "Region=\"us-east-2\" FromEmail=\"support@cloudium.net\" BucketName=\"status2.minominapr.com\""
image_repositories = []
disable_rollback = true
s3_prefix = "minomina-stacks2"
stack_name = "minomina-stacks2"

[default.package.parameters]
resolve_s3 = false

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
